### ISSUE TITLE
Do I need that to use IndexedDB?

### ISSUE THREAD

**Issue by efkan** [DickvdBrink/cordova-indexeddb#2]
Hi,

First of all, thanks for that huge works. 

I don't have great knowledge regarding Cordova. I have two questions. If you may response to them when you are available, I would be appreciated.

I wonder that can I use IndexedDB in Cordova without cordova-indexeddb?
The following link to show how to use indexed-db in a HTML application.
http://www.html5rocks.com/en/tutorials/indexeddb/todo/# 

If it works for HTML, it can works for Cordova. Doesn't it?

Have a nice day...

**Comment by najmam** [comment]
_(I know I'm answering an outdated question, but I hope this will help future visitors. I didn't use `cordova-indexeddb` yet.)_

You can use IndexedDB in a web browser [if that browser supports it](http://caniuse.com/#feat=indexeddb). Since Cordova instantiates a WebView (the stock browser) of your target platform, whether or not a Cordova application provides IndexedDB by default depends on the platform. Stock browsers are often customized by device manufacturers and rarely get updated, thus you shouldn't expect recent Web APIs to be available to them.

This kind of inconsistency is exactly what we want to avoid when using Cordova. `cordova-indexeddb`'s approach consists in [shimming](https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FShim_%28computing%29) IndexedDB using [`IndexedDBShim`](https://github.com/axemclion/IndexedDBShim), which relies on [Web SQL](https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FWeb_SQL_Database). This may be what you want, but please note that [**"[WebSQL] is no longer in active maintenance and the Web Applications Working Group does not intend to maintain it further"**](http://www.w3.org/TR/webdatabase/). In short, this means that old and new browsers [may or may not](http://www.w3.org/TR/webdatabase/) support it - test if it works for your target devices.

**Comment by efkan** [comment]
A good sharing. Thanks anyway.

**Comment by DickvdBrink** [comment]
Thanks for providing the answer, not sure how I missed this question; Sorry about that!
